#nullable enable
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace AOWorldEditor.Data;

/// <summary>
/// Per-map container for the NEW advanced light system. Mirrors the
/// load/save pattern of <see cref="MapZoneData"/> — INI-ish key=value
/// blocks with a single key per section. The on-disk file is
/// <c>MapaN.aolight</c>, alongside the existing <c>MapaN.aomap</c>.
///
/// This system is intentionally separate from the legacy primitive
/// per-tile light data carried by <see cref="MapData"/> — nothing here
/// modifies or reads from the legacy system.
/// </summary>
public class MapLightData
{
    public List<MapLight> Lights = new();
    public List<LightAsset> UserAssets = new();

    /// <summary>Load <c>MapaN.aolight</c>. Returns an empty container if
    /// the file is missing or unreadable.</summary>
    public static MapLightData Load(string dir, int mapNum)
    {
        var result = new MapLightData();
        string path = Path.Combine(dir, $"Mapa{mapNum}.aolight");
        if (!File.Exists(path)) return result;

        string[] lines;
        try { lines = File.ReadAllLines(path); }
        catch { return result; }

        string section = "";
        foreach (string raw in lines)
        {
            string line = raw.Trim();
            if (line.Length == 0 || line[0] == ';' || line[0] == '#') continue;

            if (line[0] == '[' && line[^1] == ']')
            {
                section = line[1..^1].ToUpperInvariant();
                continue;
            }

            int eq = line.IndexOf('=');
            if (eq < 0) continue;
            string key = line[..eq].Trim().ToUpperInvariant();
            string val = line[(eq + 1)..].Trim();

            if (section.StartsWith("ASSET") && key == "ASSET")
            {
                var asset = LightAsset.TryParse(val);
                if (asset != null) result.UserAssets.Add(asset);
            }
            else if (section.StartsWith("LIGHT") && key == "LIGHT")
            {
                var light = MapLight.TryParse(val);
                if (light != null) result.Lights.Add(light);
            }
        }

        return result;
    }

    /// <summary>Save to <c>MapaN.aolight</c>. If both lists are empty,
    /// any existing file is deleted instead — keeping the directory tidy.</summary>
    public void Save(string dir, int mapNum)
    {
        string path = Path.Combine(dir, $"Mapa{mapNum}.aolight");

        if (Lights.Count == 0 && UserAssets.Count == 0)
        {
            if (File.Exists(path))
            {
                try { File.Delete(path); }
                catch { /* best effort */ }
            }
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine($"; Advanced light file for map {mapNum}");
        sb.AppendLine("; Generated by AO World Editor");
        sb.AppendLine();

        for (int i = 0; i < UserAssets.Count; i++)
        {
            sb.AppendLine($"[ASSET{i + 1}]");
            sb.AppendLine($"Asset={UserAssets[i].Serialize()}");
            sb.AppendLine();
        }

        for (int i = 0; i < Lights.Count; i++)
        {
            sb.AppendLine($"[LIGHT{i + 1}]");
            sb.AppendLine($"Light={Lights[i].Serialize()}");
            sb.AppendLine();
        }

        File.WriteAllText(path, sb.ToString());
    }
}
