#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace AOWorldEditor.Data;

/// <summary>Zone type classification.</summary>
public enum ZoneType
{
    Neutral = 0,
    Safe = 1,
    PvP = 2,
    Dungeon = 3,
    Arena = 4,
}

/// <summary>NPC spawn mode within a zone.</summary>
public enum SpawnMode
{
    Fixed = 0,
    Random = 1,
}

/// <summary>A rectangular zone within a map.</summary>
public class ZoneInfo
{
    public int Id;
    public string Name = "";
    public ZoneType Type = ZoneType.Neutral;

    // Bounds (1-based tile coords, inclusive)
    public int X1, Y1, X2, Y2;

    // Safety / restrictions
    public bool Segura;
    public bool Newbie;
    public bool SinMagia;
    public bool SinInvi;
    public bool SinMascotas;
    public bool SinResucitar;
    public bool SinOcultar;
    public bool SinInvocar;
    public bool SoloClanes;
    public bool SoloFaccion;
    public int Faccion;       // 0=any, 1=real, 2=caos
    public bool CombatZone;

    // Level restriction (0 = no limit)
    public int MinLevel;
    public int MaxLevel;

    // Ambient overrides (0 = use map default)
    public int Musica;
    public bool Lluvia;
    public bool Nieve;
    public bool Niebla;
    public int NieblaDensity = 0;   // 0-255, 0=off → falls back to CPU rect
    public int NieblaR = 128;
    public int NieblaG = 140;
    public int NieblaB = 160;
    public int NieblaSpeedX = 5;    // -100..100 (roughly)
    public int NieblaSpeedY = 2;
    public int NieblaSize = 512;    // noise cell size in world pixels (64..2048)
    public int AmbientR, AmbientG, AmbientB;
    public string Terreno = "";

    // Exit point (death/expulsion). Map=0 = use default.
    public int SalidaMap, SalidaX, SalidaY;

    public bool Contains(int x, int y) =>
        x >= X1 && x <= X2 && y >= Y1 && y <= Y2;
}

/// <summary>An NPC spawn definition within a zone.</summary>
public class NpcSpawnInfo
{
    public int ZoneId;
    public int NpcIndex;
    public int Cantidad = 1;
    public SpawnMode Mode = SpawnMode.Random;
    public int SpawnX, SpawnY; // only for Fixed mode
    public int RespawnTime = 30; // seconds
}

/// <summary>All zone data for a single map. Handles load/save of .aozone files.</summary>
public class MapZoneData
{
    public List<ZoneInfo> Zones = new();
    public List<NpcSpawnInfo> Spawns = new();

    /// <summary>Load a .aozone file. Returns empty MapZoneData if file doesn't exist.</summary>
    public static MapZoneData Load(string dir, int mapNum)
    {
        var result = new MapZoneData();
        string path = Path.Combine(dir, $"Mapa{mapNum}.aozone");
        if (!File.Exists(path)) return result;

        string[] lines;
        try { lines = File.ReadAllLines(path); }
        catch { return result; }

        string section = "";
        ZoneInfo? zone = null;
        NpcSpawnInfo? spawn = null;
        int zoneCount = 0;

        foreach (string raw in lines)
        {
            string line = raw.Trim();
            if (line.Length == 0 || line[0] == ';' || line[0] == '#') continue;

            if (line[0] == '[' && line[^1] == ']')
            {
                // Save previous
                if (section.StartsWith("ZONE") && zone != null && zone.X1 > 0)
                    result.Zones.Add(zone);
                else if (section.StartsWith("SPAWN") && spawn != null && spawn.NpcIndex > 0)
                    result.Spawns.Add(spawn);

                section = line[1..^1].ToUpper();
                if (section.StartsWith("ZONE"))
                {
                    zoneCount++;
                    zone = new ZoneInfo { Id = zoneCount };
                }
                else if (section.StartsWith("SPAWN"))
                {
                    spawn = new NpcSpawnInfo();
                }
                continue;
            }

            int eq = line.IndexOf('=');
            if (eq < 0) continue;
            string key = line[..eq].Trim().ToUpper();
            string val = line[(eq + 1)..].Trim();

            if (section.StartsWith("ZONE") && zone != null)
                ParseZone(zone, key, val);
            else if (section.StartsWith("SPAWN") && spawn != null)
                ParseSpawn(spawn, key, val);
        }

        // Save last section
        if (section.StartsWith("ZONE") && zone != null && zone.X1 > 0)
            result.Zones.Add(zone);
        else if (section.StartsWith("SPAWN") && spawn != null && spawn.NpcIndex > 0)
            result.Spawns.Add(spawn);

        return result;
    }

    /// <summary>Save to .aozone file.</summary>
    public void Save(string dir, int mapNum)
    {
        string path = Path.Combine(dir, $"Mapa{mapNum}.aozone");
        var sb = new StringBuilder();
        sb.AppendLine($"; Zone file for map {mapNum}");
        sb.AppendLine("; Generated by AO World Editor");
        sb.AppendLine();

        for (int i = 0; i < Zones.Count; i++)
        {
            var z = Zones[i];
            sb.AppendLine($"[ZONE{i + 1}]");
            sb.AppendLine($"Name={z.Name}");
            sb.AppendLine($"Type={(int)z.Type}");
            sb.AppendLine($"X1={z.X1}"); sb.AppendLine($"Y1={z.Y1}");
            sb.AppendLine($"X2={z.X2}"); sb.AppendLine($"Y2={z.Y2}");
            sb.AppendLine($"Segura={(z.Segura ? 1 : 0)}");
            sb.AppendLine($"Newbie={(z.Newbie ? 1 : 0)}");
            sb.AppendLine($"SinMagia={(z.SinMagia ? 1 : 0)}");
            sb.AppendLine($"SinInvi={(z.SinInvi ? 1 : 0)}");
            sb.AppendLine($"SinMascotas={(z.SinMascotas ? 1 : 0)}");
            sb.AppendLine($"SinResucitar={(z.SinResucitar ? 1 : 0)}");
            sb.AppendLine($"SinOcultar={(z.SinOcultar ? 1 : 0)}");
            sb.AppendLine($"SinInvocar={(z.SinInvocar ? 1 : 0)}");
            sb.AppendLine($"SoloClanes={(z.SoloClanes ? 1 : 0)}");
            sb.AppendLine($"SoloFaccion={(z.SoloFaccion ? 1 : 0)}");
            sb.AppendLine($"Faccion={z.Faccion}");
            sb.AppendLine($"CombatZone={(z.CombatZone ? 1 : 0)}");
            sb.AppendLine($"MinLevel={z.MinLevel}");
            sb.AppendLine($"MaxLevel={z.MaxLevel}");
            sb.AppendLine($"Musica={z.Musica}");
            sb.AppendLine($"Lluvia={(z.Lluvia ? 1 : 0)}");
            sb.AppendLine($"Nieve={(z.Nieve ? 1 : 0)}");
            sb.AppendLine($"Niebla={(z.Niebla ? 1 : 0)}");
            sb.AppendLine($"FogDensity={z.NieblaDensity}");
            sb.AppendLine($"FogR={z.NieblaR}");
            sb.AppendLine($"FogG={z.NieblaG}");
            sb.AppendLine($"FogB={z.NieblaB}");
            sb.AppendLine($"FogSpeedX={z.NieblaSpeedX}");
            sb.AppendLine($"FogSpeedY={z.NieblaSpeedY}");
            sb.AppendLine($"FogSize={z.NieblaSize}");
            sb.AppendLine($"AmbientR={z.AmbientR}");
            sb.AppendLine($"AmbientG={z.AmbientG}");
            sb.AppendLine($"AmbientB={z.AmbientB}");
            sb.AppendLine($"Terreno={z.Terreno}");
            sb.AppendLine($"SalidaMap={z.SalidaMap}");
            sb.AppendLine($"SalidaX={z.SalidaX}");
            sb.AppendLine($"SalidaY={z.SalidaY}");
            sb.AppendLine();
        }

        for (int i = 0; i < Spawns.Count; i++)
        {
            var s = Spawns[i];
            sb.AppendLine($"[SPAWN{i + 1}]");
            sb.AppendLine($"Zone={s.ZoneId}");
            sb.AppendLine($"NpcIndex={s.NpcIndex}");
            sb.AppendLine($"Cantidad={s.Cantidad}");
            sb.AppendLine($"SpawnMode={(int)s.Mode}");
            if (s.Mode == SpawnMode.Fixed)
            {
                sb.AppendLine($"SpawnX={s.SpawnX}");
                sb.AppendLine($"SpawnY={s.SpawnY}");
            }
            sb.AppendLine($"RespawnTime={s.RespawnTime}");
            sb.AppendLine();
        }

        File.WriteAllText(path, sb.ToString());
    }

    private static void ParseZone(ZoneInfo z, string key, string val)
    {
        switch (key)
        {
            case "NAME": z.Name = val; break;
            case "TYPE": z.Type = (ZoneType)(int.TryParse(val, out int t) ? t : 0); break;
            case "X1": z.X1 = int.TryParse(val, out int x1) ? x1 : 0; break;
            case "Y1": z.Y1 = int.TryParse(val, out int y1) ? y1 : 0; break;
            case "X2": z.X2 = int.TryParse(val, out int x2) ? x2 : 0; break;
            case "Y2": z.Y2 = int.TryParse(val, out int y2) ? y2 : 0; break;
            case "SEGURA": z.Segura = val == "1"; break;
            case "NEWBIE": z.Newbie = val == "1"; break;
            case "SINMAGIA": z.SinMagia = val == "1"; break;
            case "SININVI": z.SinInvi = val == "1"; break;
            case "SINMASCOTAS": z.SinMascotas = val == "1"; break;
            case "SINRESUCITAR": z.SinResucitar = val == "1"; break;
            case "SINOCULTAR": z.SinOcultar = val == "1"; break;
            case "SININVOCAR": z.SinInvocar = val == "1"; break;
            case "SOLOCLANES": z.SoloClanes = val == "1"; break;
            case "SOLOFACCION": z.SoloFaccion = val == "1"; break;
            case "FACCION": z.Faccion = int.TryParse(val, out int f) ? f : 0; break;
            case "COMBATZONE": z.CombatZone = val == "1"; break;
            case "MINLEVEL": z.MinLevel = int.TryParse(val, out int mn) ? mn : 0; break;
            case "MAXLEVEL": z.MaxLevel = int.TryParse(val, out int mx) ? mx : 0; break;
            case "MUSICA": z.Musica = int.TryParse(val, out int mu) ? mu : 0; break;
            case "LLUVIA": z.Lluvia = val == "1"; break;
            case "NIEVE": z.Nieve = val == "1"; break;
            case "NIEBLA": z.Niebla = val == "1"; break;
            case "FOGDENSITY": z.NieblaDensity = int.TryParse(val, out int fd) ? fd : 0; break;
            case "FOGR": z.NieblaR = int.TryParse(val, out int fr) ? fr : 128; break;
            case "FOGG": z.NieblaG = int.TryParse(val, out int fg) ? fg : 140; break;
            case "FOGB": z.NieblaB = int.TryParse(val, out int fb) ? fb : 160; break;
            case "FOGSPEEDX": z.NieblaSpeedX = int.TryParse(val, out int fsx) ? fsx : 5; break;
            case "FOGSPEEDY": z.NieblaSpeedY = int.TryParse(val, out int fsy) ? fsy : 2; break;
            case "FOGSIZE": z.NieblaSize = int.TryParse(val, out int fsz) && fsz > 0 ? fsz : 512; break;
            case "AMBIENTR": z.AmbientR = int.TryParse(val, out int r) ? r : 0; break;
            case "AMBIENTG": z.AmbientG = int.TryParse(val, out int g) ? g : 0; break;
            case "AMBIENTB": z.AmbientB = int.TryParse(val, out int b) ? b : 0; break;
            case "TERRENO": z.Terreno = val; break;
            case "SALIDAMAP": z.SalidaMap = int.TryParse(val, out int sm) ? sm : 0; break;
            case "SALIDAX": z.SalidaX = int.TryParse(val, out int sx) ? sx : 0; break;
            case "SALIDAY": z.SalidaY = int.TryParse(val, out int sy) ? sy : 0; break;
        }
    }

    private static void ParseSpawn(NpcSpawnInfo s, string key, string val)
    {
        switch (key)
        {
            case "ZONE": s.ZoneId = int.TryParse(val, out int z) ? z : 0; break;
            case "NPCINDEX": s.NpcIndex = int.TryParse(val, out int n) ? n : 0; break;
            case "CANTIDAD": s.Cantidad = int.TryParse(val, out int c) ? c : 1; break;
            case "SPAWNMODE": s.Mode = val == "1" ? SpawnMode.Random : SpawnMode.Fixed; break;
            case "SPAWNX": s.SpawnX = int.TryParse(val, out int sx) ? sx : 0; break;
            case "SPAWNY": s.SpawnY = int.TryParse(val, out int sy) ? sy : 0; break;
            case "RESPAWNTIME": s.RespawnTime = int.TryParse(val, out int rt) ? rt : 30; break;
        }
    }

    /// <summary>Find which zone contains a given tile, or null if none.</summary>
    public ZoneInfo? GetZoneAt(int x, int y)
    {
        foreach (var z in Zones)
            if (z.Contains(x, y)) return z;
        return null;
    }
}
