using System;
using System.Collections.Generic;
using System.Text.Json;
using ArgentumNextgen.Data.Resources;
using Godot;

namespace ArgentumNextgen.Data;

/// <summary>
/// GRH groups the renderer needs to recognise by number: water, tree canopies
/// and a few named UI graphics.
///
/// These used to be hardcoded literals in WorldRenderer and InventoryPanel,
/// which broke the moment the catalogue was renumbered. They now come from
/// INIT/GrhCatalog.json, generated by tools/grhtool.
/// </summary>
public sealed class GrhCatalog
{
    /// <summary>Inclusive [start, end] GRH ranges drawn as water.</summary>
    public (int Start, int End)[] WaterRanges = Array.Empty<(int, int)>();

    /// <summary>GRHs drawn as tree canopies, which fade when walked under.</summary>
    private HashSet<int> _trees = new();

    private Dictionary<string, int> _ui = new();

    public bool IsWater(int grhIndex)
    {
        // Linear scan: there are only a handful of ranges, and this sits on the
        // tile-drawing path where a dictionary lookup would not be cheaper.
        foreach (var (start, end) in WaterRanges)
            if (grhIndex >= start && grhIndex <= end) return true;
        return false;
    }

    public bool IsTree(int grhIndex) => _trees.Contains(grhIndex);

    /// <summary>Named UI graphic, or <paramref name="fallback"/> when absent.</summary>
    public int Ui(string name, int fallback = 0)
        => _ui.TryGetValue(name, out int v) ? v : fallback;

    public static GrhCatalog Load(IResourceProvider resources)
    {
        var catalog = new GrhCatalog();
        try
        {
            byte[] raw = resources.ReadBytes("INIT/GrhCatalog.json");
            using var doc = JsonDocument.Parse(raw);
            var root = doc.RootElement;

            if (root.TryGetProperty("WaterRanges", out var water))
            {
                var ranges = new List<(int, int)>();
                foreach (var r in water.EnumerateArray())
                    if (r.GetArrayLength() >= 2)
                        ranges.Add((r[0].GetInt32(), r[1].GetInt32()));
                catalog.WaterRanges = ranges.ToArray();
            }

            if (root.TryGetProperty("Trees", out var trees))
                foreach (var t in trees.EnumerateArray())
                    catalog._trees.Add(t.GetInt32());

            if (root.TryGetProperty("Ui", out var ui))
                foreach (var prop in ui.EnumerateObject())
                    catalog._ui[prop.Name] = prop.Value.GetInt32();

            GD.Print($"[CATALOG] {catalog.WaterRanges.Length} rangos de agua, "
                   + $"{catalog._trees.Count} arboles, {catalog._ui.Count} graficos de UI");
        }
        catch (Exception ex)
        {
            // Not fatal: the renderer simply treats nothing as water or tree.
            GD.PrintErr($"[CATALOG] No se pudo leer GrhCatalog.json: {ex.Message}");
        }
        return catalog;
    }
}
